// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXDYJbLLCJ0XfSSmKWrwNrWleIGJE3cAI',
    appId: '1:94731935670:web:16a0769729d02491bdeb17',
    messagingSenderId: '94731935670',
    projectId: 'testchat1-38565',
    authDomain: 'testchat1-38565.firebaseapp.com',
    storageBucket: 'testchat1-38565.appspot.com',
    measurementId: 'G-HY7JT3YBQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACNR4fF8vaac6RBUxsesaov2nFI_zrtJM',
    appId: '1:94731935670:android:a0cc66968322174fbdeb17',
    messagingSenderId: '94731935670',
    projectId: 'testchat1-38565',
    storageBucket: 'testchat1-38565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV1EXuhedyxPpqyQdtmAdFVHF4j67s2hM',
    appId: '1:94731935670:ios:bb922b40f6d20e2dbdeb17',
    messagingSenderId: '94731935670',
    projectId: 'testchat1-38565',
    storageBucket: 'testchat1-38565.appspot.com',
    iosBundleId: 'com.example.dthlms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV1EXuhedyxPpqyQdtmAdFVHF4j67s2hM',
    appId: '1:94731935670:ios:bb922b40f6d20e2dbdeb17',
    messagingSenderId: '94731935670',
    projectId: 'testchat1-38565',
    storageBucket: 'testchat1-38565.appspot.com',
    iosBundleId: 'com.example.dthlms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXDYJbLLCJ0XfSSmKWrwNrWleIGJE3cAI',
    appId: '1:94731935670:web:ffe3df4bcb599886bdeb17',
    messagingSenderId: '94731935670',
    projectId: 'testchat1-38565',
    authDomain: 'testchat1-38565.firebaseapp.com',
    storageBucket: 'testchat1-38565.appspot.com',
    measurementId: 'G-4F9F37LG43',
  );
}
